/**
 * `emitTypes(spec)` — a TypeScript declaration for a connector's operations
 * (their inputs and outputs), for connectors shipped as JSON. With it,
 * `createConduit<CatalogOf<typeof gmail>>()` types `execute` exactly as it
 * would for a builder-authored connector.
 */
import type { ConnectorSpec, InputProperty, InputSchema } from '../spec/types';

const quote = (key: string) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key));

type Schemaish = InputProperty | InputSchema | Record<string, unknown>;

function typeOf(schema: Schemaish | undefined, indent: string): string {
    if (!schema) return 'unknown';
    const s = schema as Record<string, unknown>;
    const choices = Array.isArray(s.oneOf) && s.oneOf.every((c) => c && typeof c === 'object' && 'const' in c) ? (s.oneOf as { const: unknown }[]).map((c) => c.const) : (s.enum as unknown[] | undefined);
    if (choices?.length) return choices.map((c) => JSON.stringify(c)).join(' | ');
    switch (s.type) {
        case 'string':
            return 'string';
        case 'number':
        case 'integer':
            return 'number';
        case 'boolean':
            return 'boolean';
        case 'array':
            return `Array<${typeOf(s.items as Schemaish | undefined, indent)}>`;
        case 'object': {
            const props = s.properties as Record<string, Schemaish> | undefined;
            if (!props || Object.keys(props).length === 0) return 'Record<string, unknown>';
            const required = new Set((s.required as string[] | undefined) ?? []);
            const inner = `${indent}    `;
            const lines = Object.entries(props).map(([k, v]) => `${inner}${quote(k)}${required.has(k) ? '' : '?'}: ${typeOf(v, inner)};`);
            return `{\n${lines.join('\n')}\n${indent}}`;
        }
        default:
            return 'unknown';
    }
}

/** The operations' types as a TypeScript type literal. */
export function operationTypes(spec: ConnectorSpec): string {
    const lines = spec.operations.map((op) => {
        const inputs = op.inputs ? typeOf(op.inputs, '        ') : 'Record<string, never>';
        const output = op.kind === 'options' ? 'Array<{ label: string; value: unknown }>' : typeOf(op.outputs, '        ');
        return `    ${quote(op.id)}: {\n        inputs: ${inputs};\n        output: ${output};\n    };`;
    });
    return `{\n${lines.join('\n')}\n}`;
}

/**
 * A complete `.d.ts` for a connector module whose default export is the
 * spec: `import gmail from '…/gmail'` is then fully typed.
 */
export function emitTypes(spec: ConnectorSpec): string {
    return [
        '// Generated by @sigx/conduit/builder — do not edit.',
        "import type { ConnectorSpec } from '@sigx/conduit';",
        '',
        `export type Operations = ${operationTypes(spec)};`,
        '',
        `declare const connector: ConnectorSpec & { readonly id: ${JSON.stringify(spec.id)}; readonly '~types'?: Operations };`,
        'export default connector;',
        ''
    ].join('\n');
}
