/**
 * Turns builder-authored connectors into the package's shipped artifacts:
 *
 *   src/generated/<id>.ts      the spec as a typed default export (the `./<id>` subpath)
 *   src/generated/registry.ts  summaries, lazy loaders and the `Connectors` union
 *   json/<id>.json             the plain conduit/1 JSON, for non-JS consumers
 *
 * A connector with ANY validation diagnostic — error or warning — fails the
 * build. Build-time only; never shipped.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { validateConnector, type ConnectorSpec } from '@sigx/conduit';
import { operationTypes } from '@sigx/conduit/builder';

export interface GeneratedFile {
    /** Relative to the package root. */
    path: string;
    content: string;
}

const HEADER = '// Generated by scripts/generate.mjs — do not edit. Run `pnpm --filter @sigx/conduit-connectors generate`.';

export function connectorIds(root: string): string[] {
    return readdirSync(join(root, 'connectors'), { withFileTypes: true })
        .filter((d) => d.isDirectory() && existsSync(join(root, 'connectors', d.name, 'index.ts')))
        .map((d) => d.name)
        .sort();
}

/** Inline `connectors/<id>/icon.svg` as a data URI, unless the spec has an icon. */
export function withIcon(root: string, spec: ConnectorSpec): ConnectorSpec {
    const path = join(root, 'connectors', spec.id, 'icon.svg');
    if (spec.icon || !existsSync(path)) return spec;
    return { ...spec, icon: `data:image/svg+xml;base64,${readFileSync(path).toString('base64')}` };
}

/** Throws, listing every diagnostic, unless the connector is spotless. */
export function assertSpotless(spec: ConnectorSpec): void {
    const { diagnostics } = validateConnector(spec);
    if (diagnostics.length) {
        const lines = diagnostics.map((d) => `  ${d.severity} ${d.path}: ${d.message}`);
        throw new Error([`connector "${spec.id}" has ${diagnostics.length} diagnostic(s):`, ...lines].join('\n'));
    }
}

function plain(spec: ConnectorSpec): ConnectorSpec {
    // Drop the builder's phantom and any undefined values.
    return JSON.parse(JSON.stringify(spec)) as ConnectorSpec;
}

export function renderModule(spec: ConnectorSpec): string {
    const json = JSON.stringify(plain(spec), null, 4);
    return [
        HEADER,
        "import type { ConnectorSpec } from '@sigx/conduit';",
        '',
        `export type Operations = ${operationTypes(spec)};`,
        '',
        `const connector = ${json} as unknown as ConnectorSpec & { readonly id: ${JSON.stringify(spec.id)}; readonly '~types'?: Operations };`,
        '',
        'export default connector;',
        ''
    ].join('\n');
}

export function renderRegistry(specs: readonly ConnectorSpec[]): string {
    const summaries = specs.map((s) => {
        const summary: Record<string, unknown> = { id: s.id, name: s.name, version: s.version };
        for (const key of ['description', 'icon', 'categories'] as const) if (s[key] !== undefined) summary[key] = s[key];
        return summary;
    });
    const loaders = specs.map((s) => `    ${JSON.stringify(s.id)}: () => import('./${s.id}')`).join(',\n');
    const union = specs.map((s) => `typeof import('./${s.id}').default`).join(' | ') || 'never';
    return [
        HEADER,
        "import type { ConnectorSpec, ConnectorSummary } from '@sigx/conduit';",
        '',
        `export const summaries: readonly ConnectorSummary[] = ${JSON.stringify(summaries, null, 4)};`,
        '',
        `export const loaders = {\n${loaders}\n} satisfies Record<string, () => Promise<{ default: ConnectorSpec }>>;`,
        '',
        '/** Every connector in the package — `CatalogOf<Connectors>` types `execute` for all of them. */',
        `export type Connectors = ${union};`,
        ''
    ].join('\n');
}

export function generate(specs: readonly ConnectorSpec[]): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    for (const spec of specs) {
        assertSpotless(spec);
        files.push({ path: `src/generated/${spec.id}.ts`, content: renderModule(spec) });
        files.push({ path: `json/${spec.id}.json`, content: JSON.stringify(plain(spec), null, 4) + '\n' });
    }
    files.push({ path: 'src/generated/registry.ts', content: renderRegistry(specs) });
    return files;
}

/** The package.json `exports` map for these connectors (plus the fixed entries). */
export function exportsMap(ids: readonly string[]): Record<string, unknown> {
    const map: Record<string, unknown> = {
        '.': { types: './dist/index.d.ts', development: './dist/index.js', production: './dist/index.prod.js', import: './dist/index.js' }
    };
    for (const id of ids) {
        map[`./${id}`] = { types: `./dist/generated/${id}.d.ts`, development: `./dist/${id}.js`, production: `./dist/${id}.prod.js`, import: `./dist/${id}.js` };
    }
    map['./json/*'] = './json/*';
    map['./package.json'] = './package.json';
    return map;
}
